# Generated by Django 4.0.6 on 2022-07-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo',
        ),
    ]
